@SalesInventoryManagement.APISalesInventoryManagement.API_HostAddress = http://localhost:5216

GET {{SalesInventoryManagement.APISalesInventoryManagement.API_HostAddress}}/weatherforecast/
Accept: application/json

###
